# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8731d47d007392922eb4f4dd284e69a981b8f82416c315d50fcd623ba86cf86650233174eac45fa56c6d1f114cbc22a5015ba24afa864f74ab07e041fa930005

test:
  secret_key_base: 04af83312e10fda3ca0b8893e6003e676fc14d98879553d11ef7b5a3a7ea0ac06c37d4c7cbd8ab584138d6acdfe4d873a8ea4c08c87f871090dbaa4814990aea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
